service: micro-test

package:
  artifact: build/libs/demo-0.1-lambda.zip

functions:
  test:
    handler: not.used
    runtime: provided
    events:
      - http:
          path: /
          method: GET